<?php

namespace Database\Seeders;

use App\Models\RefNationality;
use Illuminate\Database\Seeder;

class RefNationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ["nationality" => "Afghan", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Albanian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Algerian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "American", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Andorran", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Angolan", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Antiguans", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Argentinean", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Armenian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Australian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Austrian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Azerbaijani", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Bahamian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Bahraini", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Bangladeshi", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Barbadian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Barbudans", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Batswana", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Belarusian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Belgian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Belizean", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Beninese", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Bhutanese", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Bolivian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Bosnian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Brazilian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "British", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Bruneian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Bulgarian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Burkinabe", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Burmese", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Burundian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Cambodian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Cameroonian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Canadian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Cape Verdean", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Central African", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Chadian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Chilean", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Chinese", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Colombian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Comoran", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Congolese", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Costa Rican", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Croatian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Cuban", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Cypriot", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Czech", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Danish", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Djibouti", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Dominican", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Dutch", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "East Timorese", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Ecuadorean", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Egyptian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Emirian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Equatorial Guinean", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Eritrean", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Estonian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Ethiopian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Fijian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Filipino", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Finnish", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "French", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Gabonese", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Gambian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Georgian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "German", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Ghanaian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Greek", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Grenadian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Guatemalan", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Guinea-Bissauan", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Guinean", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Guyanese", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Haitian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Herzegovinian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Honduran", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Hungarian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "I-Kiribati", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Icelander", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Indian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Indonesian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Iranian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Iraqi", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Irish", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Israeli", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Italian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Ivorian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Jamaican", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Japanese", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Jordanian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Kazakhstani", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Kenyan", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Kittian and Nevisian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Kuwaiti", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Kyrgyz", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Laotian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Latvian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Lebanese", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Liberian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Libyan", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Liechtensteiner", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Lithuanian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Luxembourger", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Macedonian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Malagasy", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Malawian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Malaysian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Maldivan", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Malian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Maltese", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Marshallese", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Mauritanian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Mauritian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Mexican", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Micronesian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Moldovan", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Monacan", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Mongolian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Moroccan", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Mosotho", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Motswana", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Mozambican", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Namibian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Nauruan", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Nepalese", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "New Zealander", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Nicaraguan", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Nigerian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Nigerien", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "North Korean", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Northern Irish", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Norwegian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Omani", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Pakistani", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Palauan", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Panamanian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Papua New Guinean", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Paraguayan", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Peruvian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Polish", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Portuguese", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Qatari", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Romanian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Russian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Rwandan", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Saint Lucian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Salvadoran", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Samoan", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "San Marinese", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Sao Tomean", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Saudi", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Scottish", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Senegalese", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Serbian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Seychellois", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Sierra Leonean", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Singaporean", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Slovakian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Slovenian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Solomon Islander", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Somali", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "South African", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "South Korean", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Spanish", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Sri Lankan", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Sudanese", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Surinamer", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Swazi", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Swedish", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Swiss", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Syrian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Taiwanese", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Tajik", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Tanzanian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Thai", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Togolese", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Tongan", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Trinidadian or Tobagonian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Tunisian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Turkish", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Tuvaluan", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Ugandan", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Ukrainian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Uruguayan", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Uzbekistani", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Venezuelan", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Vietnamese", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Welsh", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Yemenite", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Zambian", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Zimbabwean", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
            ["nationality" => "Others", "created_by" => 1, "created_at" => now(), "updated_at" => now()],
        ];

        RefNationality::insert($data);
    }
}
